name: CI

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: 3.13
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest ruff

            - name: Lint with Ruff
              run: ruff check .

            - name: Format with Ruff
              run: ruff format --check .

            - name: Run tests with pytest
              run: python -m pytest